[package]
name = "rust-fraud-detection"
authors = ["Philipp Schlütermann <philipp.schluetermann@udo.edu>"]
description = "robust fraud detection using NLP topic extraction"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]
# https://doc.rust-lang.org/cargo/reference/cargo-targets.html
name = "rust_fraud_detection_tools"
path = "src/lib.rs"

[[bin]]
name = "rust_fraud_detection"
path = "src/main.rs"


[dependencies]
serde = {version = "1.0", features=["derive"]}
serde_json = "1.0"
anyhow = "1.0"
bincode = "1.3.3"
itertools = {version = "0.10.5", optional=true}
csv = {version = "1.1", optional=true}
rust-bert = {version = "0.19.0", optional=true}
smartcore = {version = "0.2.1", features=["serde"], optional=true}
ndarray = {version = "0.15.0", optional=true}
rand = {version = "0.8.5", optional=true}
regex = {version = "1.6.0", optional=true}
lazy_static = {version = "1.4.0", optional=true}
words-count = {version = "0.1.3", optional=true}

[features]
default = ["server"]
server = ["rust-bert","smartcore","ndarray","rand","regex","lazy_static","words-count","itertools","csv"]
# use
# --no-default-features
# or
# default-features = false
# to import `client_send_request` to interact (via sockets) with a running "server" instance.