[package]
name = "rust-scam-detection"
authors = ["Philipp Schlütermann <philipp.schluetermann@udo.edu>"]
description = "robust scam detection using NLP topic extraction"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]
# https://doc.rust-lang.org/cargo/reference/cargo-targets.html
name = "rust_scam_detection_tools"
path = "src/lib.rs"

[[bin]]
name = "rust_scam_detection"
path = "src/main.rs"


[dependencies]

serde = "1.0"
serde_json = "1.0"
anyhow = "1.0"
itertools = "0.10.5"
csv = "1.1"
rust-bert = "0.19.0"
smartcore = {version = "0.2.1", features=["serde"]}
ndarray = "0.15.0"
rand = "0.8.5"
regex = "1.6.0"
lazy_static = "1.4.0"
words-count = "0.1.3"

[features]
default = []
